### ISSUE TITLE
Error on restarting QGIS

### ISSUE THREAD

**Issue by pcav** [PavelVeselsky/fft-convolution-filter#4]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 219, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/paolo/.qgis2/python/plugins/fft-convolution-filter-master/**init**.py", line 34, in classFactory
    from .fft_filter import FFTConvolution
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/paolo/.qgis2/python/plugins/fft-convolution-filter-master/fft_filter.py", line 26, in 
    import resources
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named resources

**Comment by PavelVeselsky** [comment]
I must have misunderstood the "How to add your plugin to this repository" section on plugins.qgis.org, specifically this: "no generated file is left in repository (ui_*.py, resources_rc.py, gen. help files…)" The code expects resource.py, which I (mistakenly) omitted as a generated file.

**Comment by PavelVeselsky** [comment]
This is due to missing resources.py file. As an autogenerated file, I shouldn't include it. As far as I understand the autogeneration process, make should be called while installing the plugin. I checked that the makefile really makes the resources.py file while called on my computer, but it might end with some error elsewhere. Reopen the issue if the problem persists.

**Comment by PavelVeselsky** [comment]
After inspecting the code of [pyplugin installer](https://github.com/qgis/QGIS/blob/master/python/pyplugin_installer/installer.py), [corresponding dialog](https://github.com/qgis/QGIS/blob/master/python/pyplugin_installer/qgsplugininstallerinstallingdialog.py) and few plugins I realized that my assumption that the makefile is executed in the installation process was probably wrong and my plugin is in fact broken due to my misunderstanding of the ["no generated file is left in repository"](https://plugins.qgis.org/) rule.

**Comment by PavelVeselsky** [comment]
Solved in version 0.1.4.
